apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-node-api
  template:
    metadata:
      labels:
        app: devops-node-api
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: devops-node-api
          image: harbor.asthrahealthtech.com/devops-sandbox/devops-node-api:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: devops-node-api-db-secret
          env:
            - name: PORT
              value: "3000"
            - name: FILE_PATH
              value: "/app/data/data.txt"
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: devops-node-api-pvc
