namespace: devops-sandbox

replicaCount: 1

image:
  repository: harbor.asthrahealthtech.com/devops-sandbox/devops-node-api
  tag: v2
  pullPolicy: Always

imagePullSecret: harbor-regcred

containerPort: 3000

service:
  name: devops-node-api-service
  port: 80
  targetPort: 3000

secret:
  name: devops-node-api-db-secret

pvc:
  name: devops-node-api-pvc
  mountPath: /app/data

env:
  PORT: "3000"
  FILE_PATH: /app/data/data.txt

ingress:
  host: hasal-devops-node-api.internal.asthrahealthtech.com
  tlsSecret: devops-node-api-tls
  issuer: letsencrypt-asthrahealthtech
